### ISSUE TITLE
Null Pointer Exception with ChromeSafari Brower

### ISSUE THREAD

**Issue by krsolutions** [pichillilorenzo/flutter_inappbrowser#26]
2018-12-16 04:01:46.255 4864-4866/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2018-12-16 04:01:46.387 24418-24418/in.krsolutions.leader E/MethodChannel#com.pichillilorenzo/flutter_inappbrowser: Failed to handle method call
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
        at com.pichillilorenzo.flutter_inappbrowser.InAppBrowserFlutterPlugin.onMethodCall(InAppBrowserFlutterPlugin.java:100)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
        at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
2018-12-16 04:01:46.400 24418-24438/in.krsolutions.leader E/flutter: [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
    PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
    <asynchronous suspension>
    #2      ChromeSafariBrowser.open (package:flutter_inappbrowser/flutter_inappbrowser.dart:491:35)
    <asynchronous suspension>
    #3      _InAppNativeBrowserWidgetState.build.<anonymous closure> (package:leader/widgets/InAppNativeBrowserWidget.dart:75:82)
    #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
    #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
    #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
    #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
    #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
    #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
    #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
    #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
    #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
    #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
    #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
    #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
    #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
    #17     _invoke1 (dart:ui/hooks.dart:168:13)
    #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
2018-12-16 04:01:54.845 624-624/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 4
2018-12-16 04:01:57.085 624-624/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 4
2018-12-16 04:01:59.857 624-624/? E/cnss-daemon: Stale or unreachable neighbors, ndm state: 4

**Comment by pichillilorenzo** [comment]
Should be fixed with the new version **0.6.0**!
