### ISSUE TITLE
app force close/crash when enabling zoom and repeatedly changing orientation and zoomin zoomout

### ISSUE THREAD

**Issue by karnadii** [pichillilorenzo/flutter_inappbrowser#93]
code
```
InAppWebView(
    initialUrl: "http://0.0.0.0:8082?url=" + rB.currentChapter.slug,
    initialOptions: {
          "builtInZoomControls":true
    },
)
```
stacktrace
```
[+3680 ms] F/google-breakpad(30221): Microdump skipped (uninteresting)
[        ] E/BufferQueueProducer(28192): [SurfaceTexture-0-28192-0] dequeueBuffer: BufferQueue has been abandoned
[  +73 ms] W/google-breakpad(28192): ### ### ### ### ### ### ### ### ### ### ### ### ###
[        ] W/google-breakpad(28192): Chrome build fingerprint:
[        ] W/google-breakpad(28192): 70.0.3538.80
[        ] W/google-breakpad(28192): 353808050
[        ] W/google-breakpad(28192): ### ### ### ### ### ### ### ### ### ### ### ### ###
[ +126 ms] W/System.err(28192): android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@f208671 is not valid; is your activity running?
[  +10 ms] W/System.err(28192): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:589)
[        ] W/System.err(28192): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
[        ] W/System.err(28192): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
[        ] W/System.err(28192): 	at android.widget.ZoomButtonsController.setVisible(ZoomButtonsController.java:370)
[        ] W/System.err(28192): 	at Aa.a(PG:6)
[        ] W/System.err(28192): 	at yk.d(PG:29)
[        ] W/System.err(28192): 	at org.chromium.content.browser.GestureListenerManagerImpl.onEventAck(PG:53)
[        ] W/System.err(28192): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] W/System.err(28192): 	at android.os.MessageQueue.next(MessageQueue.java:323)
[   +1 ms] W/System.err(28192): 	at android.os.Looper.loop(Looper.java:141)
[        ] W/System.err(28192): 	at android.app.ActivityThread.main(ActivityThread.java:5603)
[        ] W/System.err(28192): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] W/System.err(28192): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
[   +1 ms] W/System.err(28192): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
[        ] F/chromium(28192): [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
[        ] F/libc    (28192): Fatal signal 5 (SIGTRAP), code 1 in tid 28192 (.kiryuu.co.lite)
[  +63 ms] *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
[   +1 ms] Build fingerprint: 'Xiaomi/kenzo/kenzo:6.0.1/MMB29M/8.11.22:user/release-keys'
[        ] Revision: '0'
[        ] ABI: 'arm64'
[        ] pid: 28192, tid: 28192, name: .kiryuu.co.lite  >>> app.kiryuu.co.lite <<<
[   +1 ms] signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x298100006e20
[  +61 ms] Abort message: '[FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
[        ] '
[        ]     x0   0000007fcb4ae7a0  x1   00000055948faae0  x2   0000000000000400  x3   0000007fa1500fe8
[        ]     x4   0000000000000000  x5   0000000000004001  x6   0000000000000000  x7   0000007fa10e6ad4
[        ]     x8   0000000000000000  x9   0000000000000000  x10  0000007fa10e6ad4  x11  0000000000004000
[        ]     x12  0000000000004001  x13  0000000000000000  x14  0000000000000001  x15  0000007f9dfb6158
[        ]     x16  0000007fa10d8a58  x17  0000000000000000  x18  0000007fa10e6a98  x19  0000007fcb4aec18
[        ]     x20  0000007fcb4aec10  x21  000000000000004f  x22  0000007fa10db518  x23  0000007f8d2d0000
[        ]     x24  00000000000000b0  x25  0000007fa1501098  x26  0000007fcb4ae769  x27  0000007fcb4ae768
[        ]     x28  0000007fa144260c  x29  0000007fcb4aec00  x30  0000007f8b7c5ec4
[        ]     sp   0000007fcb4ae760  pc   0000007f8b7c5fe8  pstate 0000000080000000
[   +3 ms] backtrace:
[        ]     #00 pc 0000000001c81fe8  /data/app/com.google.android.webview-2/lib/arm64/libwebviewchromium.so (offset 0xc1f000)
[        ]     #01 pc 0000000001c81ec0  /data/app/com.google.android.webview-2/lib/arm64/libwebviewchromium.so (offset 0xc1f000)
[+1217 ms] Tombstone written to: /data/tombstones/tombstone_09
[ +346 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +5 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/app.kiryuu.co.lite/code_cache/kiryuuXZWUJZ/kiryuu/)
[   +2 ms] Sending to VM service: _deleteDevFS({fsName: kiryuu})
[ +254 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +7 ms] "flutter run" took 480,465ms.
[        ] "flutter run" took 480,465ms.
flutter run --verbose --flavor pro  32.08s user 6.42s system 7% cpu 8:06.86 total
```

**Comment by pichillilorenzo** [comment]
This should be fixed with the new version **1.2.0**
